### ISSUE TITLE
Odoo gets stuck when dropping files to form view that opened by a pop up form view

### ISSUE THREAD

**Issue by TimLai125** [cytex124/odoo-drag-and-drop#9]
Impacted versions:
11.0c

Steps to reproduce:
1. Open purchase order form view.
2. Add a new order line.
3. Click the product of the order line.
4. Click the product link in the popped up form view and close the pop up.
5. Drag and drop file(s) the form view.
** Please refer to the https://drive.google.com/file/d/1DmBzerYoffGKsP_3okuvGRDUHWmlA51M/view

Current behavior:
1. Odoo stucks on the loading screen
2. A JavaScript error is occured
3. Images are uploaded 

```
Error:
Uncaught TypeError: Cannot read property 'updateEnv' of undefined

https://************/web/content/18417-1a6c7cd/web.assets_backend.js:2655
Traceback:
TypeError: Cannot read property 'updateEnv' of undefined
    at HTMLDocument.<anonymous> (https://************/web/content/18417-1a6c7cd/web.assets_backend.js:2655:524)
    at HTMLDocument.dispatch (https://************/web/content/18328-3d6dc82/web.assets_common.js:892:451)
    at HTMLDocument.elemData.handle (https://************/web/content/18328-3d6dc82/web.assets_common.js:865:173)
    at Object.trigger (https://************/web/content/18328-3d6dc82/web.assets_common.js:886:211)
    at HTMLDocument.<anonymous> (https://************/web/content/18328-3d6dc82/web.assets_common.js:937:147)
    at Function.each (https://************/web/content/18328-3d6dc82/web.assets_common.js:625:767)
    at jQuery.fn.init.each (https://************/web/content/18328-3d6dc82/web.assets_common.js:613:643)
    at jQuery.fn.init.trigger (https://************/web/content/18328-3d6dc82/web.assets_common.js:937:118)
    at https://************/web/content/18417-1a6c7cd/web.assets_backend.js:2656:440
    at Object.success (https://************/web/content/18417-1a6c7cd/web.assets_backend.js:2655:247)
```

**Comment by TimLai125** [comment]
@cytex124 Hi, please check and let me know your opninion on this topic.

**Comment by cytex124** [comment]
Hi,

thx for the details.

I can reproduce the error.  I will update the module as soon as possible and inform your by closing this issue.

Best regards,

Andy

**Comment by TimLai125** [comment]
Hi @cytex124 

Thank you for the follow-up. Please let me know if you have any ideas about the error at this moment. I wonder whether if it is some limitations of Odoo?

**Comment by cytex124** [comment]
Hi @TimLai125, 

No there was a mistake generated by me. I didn´t cleaned up the event after navigation somewhere else...
I made a update. Please feel free to download it.
After that update the module and restart the service.

Also: 
If you like I could do a translation to japanese on this module. But I also need help to translate it correctly. If you have some time just send me a message to: andreas.wyrobek95@gmail.com
